Update copy_volume.py
needs to be converted to `str`, otherwise if is determined from data, it will fail with:

```
    dtype = "u" + dtype
TypeError: can only concatenate str (not "numpy.dtype[int8]") to str
```